### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by arose13** [sdispater/pendulum#130]
The title is self-explanatory. `pip install pendulum` on windows causes the following.

```
Collecting pendulum
  Using cached pendulum-1.2.4.tar.gz
Requirement already satisfied: tzlocal in c:\users\antho\miniconda3\lib\site-packages (from pendulum)
Requirement already satisfied: python-dateutil in c:\users\antho\miniconda3\lib\site-packages (from pendulum)
Requirement already satisfied: pytzdata in c:\users\antho\miniconda3\lib\site-packages (from pendulum)
Requirement already satisfied: pytz in c:\users\antho\miniconda3\lib\site-packages (from tzlocal->pendulum)
Requirement already satisfied: six>=1.5 in c:\users\antho\miniconda3\lib\site-packages (from python-dateutil->pendulum)
Building wheels for collected packages: pendulum
  Running setup.py bdist_wheel for pendulum ... error
  Complete output from command C:\Users\antho\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\antho\\AppData\\Local\\Temp\\pip-build-z1lho91z\\pendulum\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\antho\AppData\Local\Temp\tmpp6km6hxrpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.5
  creating build\lib.win32-3.5\pendulum
  copying pendulum\constants.py -> build\lib.win32-3.5\pendulum
  copying pendulum\date.py -> build\lib.win32-3.5\pendulum
  copying pendulum\exceptions.py -> build\lib.win32-3.5\pendulum
  copying pendulum\helpers.py -> build\lib.win32-3.5\pendulum
  copying pendulum\interval.py -> build\lib.win32-3.5\pendulum
  copying pendulum\parser.py -> build\lib.win32-3.5\pendulum
  copying pendulum\pendulum.py -> build\lib.win32-3.5\pendulum
  copying pendulum\period.py -> build\lib.win32-3.5\pendulum
  copying pendulum\time.py -> build\lib.win32-3.5\pendulum
  copying pendulum\translator.py -> build\lib.win32-3.5\pendulum
  copying pendulum\version.py -> build\lib.win32-3.5\pendulum
  copying pendulum\_compat.py -> build\lib.win32-3.5\pendulum
  copying pendulum\_global.py -> build\lib.win32-3.5\pendulum
  copying pendulum\__init__.py -> build\lib.win32-3.5\pendulum
  creating build\lib.win32-3.5\pendulum\formatting
  copying pendulum\formatting\alternative_formatter.py -> build\lib.win32-3.5\pendulum\formatting
  copying pendulum\formatting\classic_formatter.py -> build\lib.win32-3.5\pendulum\formatting
  copying pendulum\formatting\difference_formatter.py -> build\lib.win32-3.5\pendulum\formatting
  copying pendulum\formatting\formatter.py -> build\lib.win32-3.5\pendulum\formatting
  copying pendulum\formatting\__init__.py -> build\lib.win32-3.5\pendulum\formatting
  creating build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\af.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\ar.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\az.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\bg.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\bn.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\ca.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\cs.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\da.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\de.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\el.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\en.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\eo.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\es.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\et.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\eu.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\fa.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\fi.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\fo.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\fr.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\gl.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\he.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\hr.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\hu.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\hy.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\id.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\it.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\ja.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\ka.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\ko.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\lt.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\lv.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\mk.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\ms.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\nl.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\nn.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\pl.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\pt_br.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\ro.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\ru.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\sk.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\sl.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\sq.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\sr.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\sv.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\th.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\tr.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\uk.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\uz.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\vi.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\zh.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\zh_tw.py -> build\lib.win32-3.5\pendulum\lang
  copying pendulum\lang\__init__.py -> build\lib.win32-3.5\pendulum\lang
  creating build\lib.win32-3.5\pendulum\mixins
  copying pendulum\mixins\default.py -> build\lib.win32-3.5\pendulum\mixins
  copying pendulum\mixins\interval.py -> build\lib.win32-3.5\pendulum\mixins
  copying pendulum\mixins\__init__.py -> build\lib.win32-3.5\pendulum\mixins
  creating build\lib.win32-3.5\pendulum\parsing
  copying pendulum\parsing\parser.py -> build\lib.win32-3.5\pendulum\parsing
  copying pendulum\parsing\__init__.py -> build\lib.win32-3.5\pendulum\parsing
  creating build\lib.win32-3.5\pendulum\tz
  copying pendulum\tz\exceptions.py -> build\lib.win32-3.5\pendulum\tz
  copying pendulum\tz\loader.py -> build\lib.win32-3.5\pendulum\tz
  copying pendulum\tz\local_timezone.py -> build\lib.win32-3.5\pendulum\tz
  copying pendulum\tz\timezone.py -> build\lib.win32-3.5\pendulum\tz
  copying pendulum\tz\timezone_info.py -> build\lib.win32-3.5\pendulum\tz
  copying pendulum\tz\transition.py -> build\lib.win32-3.5\pendulum\tz
  copying pendulum\tz\transition_type.py -> build\lib.win32-3.5\pendulum\tz
  copying pendulum\tz\__init__.py -> build\lib.win32-3.5\pendulum\tz
  creating build\lib.win32-3.5\pendulum\_extensions
  copying pendulum\_extensions\helpers.py -> build\lib.win32-3.5\pendulum\_extensions
  copying pendulum\_extensions\__init__.py -> build\lib.win32-3.5\pendulum\_extensions
  creating build\lib.win32-3.5\pendulum\parsing\exceptions
  copying pendulum\parsing\exceptions\__init__.py -> build\lib.win32-3.5\pendulum\parsing\exceptions
  running egg_info
  writing requirements to pendulum.egg-info\requires.txt
  writing dependency_links to pendulum.egg-info\dependency_links.txt
  writing pendulum.egg-info\PKG-INFO
  writing top-level names to pendulum.egg-info\top_level.txt
  reading manifest file 'pendulum.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'test*'
  writing manifest file 'pendulum.egg-info\SOURCES.txt'
  copying pendulum\_extensions\_helpers.c -> build\lib.win32-3.5\pendulum\_extensions
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\antho\AppData\Local\Temp\pip-build-z1lho91z\pendulum\setup.py", line 114, in <module>
      setup(**kwargs)
    File "C:\Users\antho\Miniconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\antho\Miniconda3\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\Users\antho\Miniconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\antho\Miniconda3\lib\site-packages\wheel\bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "C:\Users\antho\Miniconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\antho\Miniconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\antho\Miniconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\antho\Miniconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\antho\Miniconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\antho\AppData\Local\Temp\pip-build-z1lho91z\pendulum\setup.py", line 58, in run
      build_ext.run(self)
    File "C:\Users\antho\Miniconda3\lib\distutils\command\build_ext.py", line 308, in run
      force=self.force)
    File "C:\Users\antho\Miniconda3\lib\distutils\ccompiler.py", line 1031, in new_compiler
      return klass(None, dry_run, force)
    File "C:\Users\antho\Miniconda3\lib\distutils\cygwinccompiler.py", line 285, in __init__
      CygwinCCompiler.__init__ (self, verbose, dry_run, force)
    File "C:\Users\antho\Miniconda3\lib\distutils\cygwinccompiler.py", line 129, in __init__
      if self.ld_version >= "2.10.90":
  TypeError: unorderable types: NoneType() >= str()

  ----------------------------------------
  Failed building wheel for pendulum
  Running setup.py clean for pendulum
Failed to build pendulum
Installing collected packages: pendulum
  Running setup.py install for pendulum ... error
    Complete output from command C:\Users\antho\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\antho\\AppData\\Local\\Temp\\pip-build-z1lho91z\\pendulum\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\antho\AppData\Local\Temp\pip-phchmk7s-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.5
    creating build\lib.win32-3.5\pendulum
    copying pendulum\constants.py -> build\lib.win32-3.5\pendulum
    copying pendulum\date.py -> build\lib.win32-3.5\pendulum
    copying pendulum\exceptions.py -> build\lib.win32-3.5\pendulum
    copying pendulum\helpers.py -> build\lib.win32-3.5\pendulum
    copying pendulum\interval.py -> build\lib.win32-3.5\pendulum
    copying pendulum\parser.py -> build\lib.win32-3.5\pendulum
    copying pendulum\pendulum.py -> build\lib.win32-3.5\pendulum
    copying pendulum\period.py -> build\lib.win32-3.5\pendulum
    copying pendulum\time.py -> build\lib.win32-3.5\pendulum
    copying pendulum\translator.py -> build\lib.win32-3.5\pendulum
    copying pendulum\version.py -> build\lib.win32-3.5\pendulum
    copying pendulum\_compat.py -> build\lib.win32-3.5\pendulum
    copying pendulum\_global.py -> build\lib.win32-3.5\pendulum
    copying pendulum\__init__.py -> build\lib.win32-3.5\pendulum
    creating build\lib.win32-3.5\pendulum\formatting
    copying pendulum\formatting\alternative_formatter.py -> build\lib.win32-3.5\pendulum\formatting
    copying pendulum\formatting\classic_formatter.py -> build\lib.win32-3.5\pendulum\formatting
    copying pendulum\formatting\difference_formatter.py -> build\lib.win32-3.5\pendulum\formatting
    copying pendulum\formatting\formatter.py -> build\lib.win32-3.5\pendulum\formatting
    copying pendulum\formatting\__init__.py -> build\lib.win32-3.5\pendulum\formatting
    creating build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\af.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\ar.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\az.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\bg.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\bn.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\ca.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\cs.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\da.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\de.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\el.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\en.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\eo.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\es.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\et.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\eu.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\fa.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\fi.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\fo.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\fr.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\gl.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\he.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\hr.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\hu.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\hy.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\id.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\it.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\ja.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\ka.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\ko.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\lt.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\lv.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\mk.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\ms.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\nl.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\nn.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\pl.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\pt_br.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\ro.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\ru.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\sk.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\sl.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\sq.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\sr.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\sv.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\th.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\tr.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\uk.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\uz.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\vi.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\zh.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\zh_tw.py -> build\lib.win32-3.5\pendulum\lang
    copying pendulum\lang\__init__.py -> build\lib.win32-3.5\pendulum\lang
    creating build\lib.win32-3.5\pendulum\mixins
    copying pendulum\mixins\default.py -> build\lib.win32-3.5\pendulum\mixins
    copying pendulum\mixins\interval.py -> build\lib.win32-3.5\pendulum\mixins
    copying pendulum\mixins\__init__.py -> build\lib.win32-3.5\pendulum\mixins
    creating build\lib.win32-3.5\pendulum\parsing
    copying pendulum\parsing\parser.py -> build\lib.win32-3.5\pendulum\parsing
    copying pendulum\parsing\__init__.py -> build\lib.win32-3.5\pendulum\parsing
    creating build\lib.win32-3.5\pendulum\tz
    copying pendulum\tz\exceptions.py -> build\lib.win32-3.5\pendulum\tz
    copying pendulum\tz\loader.py -> build\lib.win32-3.5\pendulum\tz
    copying pendulum\tz\local_timezone.py -> build\lib.win32-3.5\pendulum\tz
    copying pendulum\tz\timezone.py -> build\lib.win32-3.5\pendulum\tz
    copying pendulum\tz\timezone_info.py -> build\lib.win32-3.5\pendulum\tz
    copying pendulum\tz\transition.py -> build\lib.win32-3.5\pendulum\tz
    copying pendulum\tz\transition_type.py -> build\lib.win32-3.5\pendulum\tz
    copying pendulum\tz\__init__.py -> build\lib.win32-3.5\pendulum\tz
    creating build\lib.win32-3.5\pendulum\_extensions
    copying pendulum\_extensions\helpers.py -> build\lib.win32-3.5\pendulum\_extensions
    copying pendulum\_extensions\__init__.py -> build\lib.win32-3.5\pendulum\_extensions
    creating build\lib.win32-3.5\pendulum\parsing\exceptions
    copying pendulum\parsing\exceptions\__init__.py -> build\lib.win32-3.5\pendulum\parsing\exceptions
    running egg_info
    writing top-level names to pendulum.egg-info\top_level.txt
    writing pendulum.egg-info\PKG-INFO
    writing dependency_links to pendulum.egg-info\dependency_links.txt
    writing requirements to pendulum.egg-info\requires.txt
    reading manifest file 'pendulum.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching 'test*'
    writing manifest file 'pendulum.egg-info\SOURCES.txt'
    copying pendulum\_extensions\_helpers.c -> build\lib.win32-3.5\pendulum\_extensions
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\antho\AppData\Local\Temp\pip-build-z1lho91z\pendulum\setup.py", line 114, in <module>
        setup(**kwargs)
      File "C:\Users\antho\Miniconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\antho\Miniconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\antho\Miniconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\antho\Miniconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\antho\Miniconda3\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "C:\Users\antho\Miniconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\antho\Miniconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\antho\Miniconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\antho\Miniconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\antho\Miniconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\antho\AppData\Local\Temp\pip-build-z1lho91z\pendulum\setup.py", line 58, in run
        build_ext.run(self)
      File "C:\Users\antho\Miniconda3\lib\distutils\command\build_ext.py", line 308, in run
        force=self.force)
      File "C:\Users\antho\Miniconda3\lib\distutils\ccompiler.py", line 1031, in new_compiler
        return klass(None, dry_run, force)
      File "C:\Users\antho\Miniconda3\lib\distutils\cygwinccompiler.py", line 285, in __init__
        CygwinCCompiler.__init__ (self, verbose, dry_run, force)
      File "C:\Users\antho\Miniconda3\lib\distutils\cygwinccompiler.py", line 129, in __init__
        if self.ld_version >= "2.10.90":
    TypeError: unorderable types: NoneType() >= str()

    ----------------------------------------
Command "C:\Users\antho\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\antho\\AppData\\Local\\Temp\\pip-build-z1lho91z\\pendulum\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\antho\AppData\Local\Temp\pip-phchmk7s-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\antho\AppData\Local\Temp\pip-build-z1lho91z\pendulum\
```

Cheers folks!

**Comment by sdispater** [comment]
This is not specific to pendulum but rather an issue with building C extensions.

You might want to look at https://stackoverflow.com/questions/24683305/python-cant-install-packages-typeerror-unorderable-types-nonetype-str to see if it solves your issue.
