### ISSUE TITLE
Pendulum.astimezone crashes with dateutil.tz.tzlocal

### ISSUE THREAD

**Issue by touilleMan** [sdispater/pendulum#186]
Using pendulum 1.4.2 and 2.7.0:

```python
(venv) >>> import pendulum
(venv) >>> dt = pendulum.now()
(venv) >>> import dateutil
(venv) >>> dt.astimezone(dateutil.tz.tzlocal())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/emmanuel/projects/sief-back/venv/lib/python3.5/site-packages/pendulum/pendulum.py", line 1960, in astimezone
    tz = self._safe_create_datetime_zone(tz)
  File "/home/emmanuel/projects/sief-back/venv/lib/python3.5/site-packages/pendulum/pendulum.py", line 80, in _safe_create_datetime_zone
    return FixedTimezone.load(obj.utcoffset(None).total_seconds())
AttributeError: 'NoneType' object has no attribute 'total_seconds'
```

I've fixed this crash by monkeypatching `Pendulum._safe_create_datetime_zone`:
```python
@classmethod
def patched_Pendulum_safe_create_datetime_zone(cls, obj):
    if isinstance(obj, tzlocal):
        obj = None
    return cls._vanilla_safe_create_datetime_zone(obj)

Pendulum._vanilla_safe_create_datetime_zone = Pendulum._safe_create_datetime_zone
Pendulum._safe_create_datetime_zone = patched_Pendulum_safe_create_datetime_zone
```

I can provide a PR if you think this is the correct way to address this bug ;-)

**Comment by sdispater** [comment]
This bug no longer occurs in the latest stables releases
