### ISSUE TITLE
Alternative parser doesn't support locale tokens in from_format() method

### ISSUE THREAD

**Issue by Canuteson** [sdispater/pendulum#193]
pendulum.from_format can create a datetime object using the classic formatter with Localized month token `%b`, but cannot using the alternative formatter. Alternative formatter should support using localized months before the classic formatter is fully deprecated.

eg:
```
>>> datestring = '05/Mar/2018:15:25:33+0000'
>>> pendulum.from_format(datestring, '%d/%b/%Y:%H:%M:%S+%f')
<Pendulum [2018-03-05T15:25:33+00:00]>
```
Alternative formatter fails using the format `'DD/MMM/YYYY:HH:mm:ss+SSSS'`
```
>>> pendulum.from_format(datestring, 'DD/MMM/YYYY:HH:mm:ss+SSSS', formatter='alternative')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "${HOME}/.virtualenvs/venv/local/lib/python2.7/site-packages/pendulum/pendulum.py", line 415, in create_from_format
    parts = formatter.parse(time, fmt)
  File "${HOME}/.virtualenvs/venv/local/lib/python2.7/site-packages/pendulum/formatting/alternative_formatter.py", line 355, in parse
    pattern = self._FORMAT_RE.sub(lambda m: self._replace_tokens(m.group(0)), fmt)
  File "${HOME}/.virtualenvs/venv/local/lib/python2.7/site-packages/pendulum/formatting/alternative_formatter.py", line 355, in <lambda>
    pattern = self._FORMAT_RE.sub(lambda m: self._replace_tokens(m.group(0)), fmt)
  File "${HOME}/.virtualenvs/venv/local/lib/python2.7/site-packages/pendulum/formatting/alternative_formatter.py", line 408, in _replace_tokens
    raise ValueError('Unsupported token: {}'.format(token))
ValueError: Unsupported token: MMM

```

**Comment by sdispater** [comment]
The "locale" tokens have been added in the soon-to-be-released version `2.0`. It was possible to do it thanks to the revamp of the locale system.

In versions `1.x` it would take some work to add it so I am not sure about this. But if someone wants to tackle this and make a PR I'd gladly review it and merge it.

**Comment by Canuteson** [comment]
Ok, I was worried about this due to deprecation warnings about using the classic formatter. I tried switching to the alternative formatter ahead of the 2.0 release. Will just wait until 2.0 to switch my formatter.
