### ISSUE TITLE
TypeError: invalid file: <_io.BufferedReader name='/etc/localtime'>

### ISSUE THREAD

**Issue by mayfield** [sdispater/pendulum#21]
* Fedora 24
* Python3.5 (distro)
* pip3 install pendulum (version 0.5)

I get this error on a fairly stock fedora box.

```
>>> pendulum.now()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.5/site-packages/pendulum/pendulum.py", line 270, in now
    return cls.instance(dt, tz)
  File "/usr/lib64/python3.5/site-packages/pendulum/pendulum.py", line 205, in instance
    tzinfo=tz
  File "/usr/lib64/python3.5/site-packages/pendulum/pendulum.py", line 180, in __init__
    self._tz = self._safe_create_datetime_zone(tzinfo)
  File "/usr/lib64/python3.5/site-packages/pendulum/pendulum.py", line 111, in _safe_create_datetime_zone
    return cls._local_timezone()
  File "/usr/lib64/python3.5/site-packages/pendulum/pendulum.py", line 130, in _local_timezone
    return local_timezone()
  File "/usr/lib64/python3.5/site-packages/pendulum/tz/__init__.py", line 25, in local_timezone
    return LocalTimezone.get()
  File "/usr/lib64/python3.5/site-packages/pendulum/tz/local_timezone.py", line 19, in get
    name = cls.get_local_tz_name()
  File "/usr/lib64/python3.5/site-packages/pendulum/tz/local_timezone.py", line 36, in get_local_tz_name
    return getattr(cls, 'get_tz_name_for_{}'.format(os))()
  File "/usr/lib64/python3.5/site-packages/pendulum/tz/local_timezone.py", line 145, in get_tz_name_for_unix
    return Timezone('', *Parser.parse(tzfile))
  File "/usr/lib64/python3.5/site-packages/pendulum/tz/parser.py", line 27, in parse
    with open(filepath, 'rb') as fp:
TypeError: invalid file: <_io.BufferedReader name='/etc/localtime'>
```

**Comment by mayfield** [comment]
FYI: `/etc/localtime` is a symlink to `/usr/share/zoneinfo/America/Boise` in my case.

**Comment by sdispater** [comment]
I think it's linked to #18 that I just merged on `master`.

Can you install `pendulum` from the master branch to see if it fixes the error?

**Comment by mayfield** [comment]
Indeed it does.  When's the next pypi release come out?

**Comment by sdispater** [comment]
I will try to release a quick fix version either today by the end of the day (for me) or tomorrow.

**Comment by sdispater** [comment]
Version `0.5.1` has just been released.
