### ISSUE TITLE
Timezone is expected to be string

### ISSUE THREAD

**Issue by yardensachs** [sdispater/pendulum#225]
Python 3.6.4
Pendulum 2.0.2

When saving a datetime field in Django with a pendulum value, there is a crash happening:
This does not happen in pendulum 1.X

## Example:
```python
import datetime
import pendulum
from django.db import models

# Model example
class ModelName(models.Model):
    datefield = models.DateTimeField()

# Saving pendulum
ModelName(
    datefield=pendulum.instance(datetime.datetime.now()),
).save()
```

```python
Traceback (most recent call last):
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/django/db/models/base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/django/db/models/base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/django/db/models/query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1283, in execute_sql
    for sql, params in self.as_sql():
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1236, in as_sql
    for obj in self.query.objs
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1236, in <listcomp>
    for obj in self.query.objs
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1235, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1175, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 767, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1431, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1425, in get_prep_value
    value = timezone.make_aware(value, default_timezone)
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/django/utils/timezone.py", line 269, in make_aware
    return timezone.localize(value, is_dst=is_dst)
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/pytz/__init__.py", line 224, in localize
    return dt.replace(tzinfo=self)
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/pendulum/datetime.py", line 1414, in replace
    dst_rule=transition_rule
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/pendulum/__init__.py", line 100, in datetime
    tz = _safe_timezone(tz)
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/pendulum/__init__.py", line 82, in _safe_timezone
    return timezone(obj)
  File "/Users/user/.virtualenvs/env/lib/python3.6/site-packages/pendulum/tz/__init__.py", line 30, in timezone
    if name.lower() == 'utc':
AttributeError: 'FixedTimezone' object has no attribute 'lower'
````

**Comment by techdragon** [comment]
I just ran into this while trying to use a timezone object when converting some code over from Arrow.

This works fine.
```python
arrow.now(tz=myobject.timezone)
```
But this fails with a traceback.
```python
pendulum.now(myobject.timezone)
```
this also fails with the same traceback. 
```python
pendulum.now(tz=myobject.timezone)
```
Both of these pendulum examples fail with this traceback:
```
Traceback (most recent call last):
  File "/Users/sam/dev/scratchpad/venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-a8d0c8b429a5>", line 1, in <module>
    pendulum.now(tz=myobject.timezone)
  File "/Users/sam/dev/scratchpad/venv/lib/python3.6/site-packages/pendulum/__init__.py", line 212, in now
    tz = _safe_timezone(tz)
  File "/Users/sam/dev/scratchpad/venv/lib/python3.6/site-packages/pendulum/__init__.py", line 82, in _safe_timezone
    return timezone(obj)
  File "/Users/sam/dev/scratchpad/venv/lib/python3.6/site-packages/pendulum/tz/__init__.py", line 30, in timezone
    if name.lower() == 'utc':
AttributeError: 'Timezone' object has no attribute 'lower'
```

**Comment by yardensachs** [comment]
@sdispater any news on this one?
