### ISSUE TITLE
Cannot parse UTC+0 style timezone

### ISSUE THREAD

**Issue by touilleMan** [sdispater/pendulum#232]
Considering the script:
```python
import pendulum
from libfaketime import fake_time, reexec_if_needed

reexec_if_needed()

if __name__ == '__main__':
    with fake_time('1970-01-01 00:00:01'):
    	pendulum.now()
```

Executing it crashes with the following stacktrace:
```
$ python ttt.py
re-exec with libfaketime dependencies
Traceback (most recent call last):
  File "/mnt/f/projects/parsec-cloud/venv/lib/python3.6/site-packages/pendulum/tz/zoneinfo/reader.py", line 48, in read_for
    file_path = pytzdata.tz_path(timezone)
  File "/mnt/f/projects/parsec-cloud/venv/lib/python3.6/site-packages/pytzdata/__init__.py", line 74, in tz_path
    raise TimezoneNotFound('Timezone {} not found at {}'.format(name, filepath))
pytzdata.exceptions.TimezoneNotFound: Timezone UTC+0 not found at /mnt/f/projects/parsec-cloud/venv/lib/python3.6/site-packages/pytzdata/zoneinfo/UTC+0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ttt.py", line 8, in <module>
    pendulum.now()
  File "/mnt/f/projects/parsec-cloud/venv/lib/python3.6/site-packages/pendulum/__init__.py", line 207, in now
    dt = _datetime.datetime.now(local_timezone())
  File "/mnt/f/projects/parsec-cloud/venv/lib/python3.6/site-packages/pendulum/tz/__init__.py", line 59, in local_timezone
    return get_local_timezone()
  File "/mnt/f/projects/parsec-cloud/venv/lib/python3.6/site-packages/pendulum/tz/local_timezone.py", line 31, in get_local_timezone
    tz = _get_system_timezone()
  File "/mnt/f/projects/parsec-cloud/venv/lib/python3.6/site-packages/pendulum/tz/local_timezone.py", line 59, in _get_system_timezone
    return _get_unix_timezone()
  File "/mnt/f/projects/parsec-cloud/venv/lib/python3.6/site-packages/pendulum/tz/local_timezone.py", line 153, in _get_unix_timezone
    return _tz_from_env(tzenv)
  File "/mnt/f/projects/parsec-cloud/venv/lib/python3.6/site-packages/pendulum/tz/local_timezone.py", line 251, in _tz_from_env
    return Timezone(tzenv)
  File "/mnt/f/projects/parsec-cloud/venv/lib/python3.6/site-packages/pendulum/tz/timezone.py", line 30, in __init__
    tz = read(name, extend=extended)
  File "/mnt/f/projects/parsec-cloud/venv/lib/python3.6/site-packages/pendulum/tz/zoneinfo/__init__.py", line 9, in read
    return Reader(extend=extend).read_for(name)
  File "/mnt/f/projects/parsec-cloud/venv/lib/python3.6/site-packages/pendulum/tz/zoneinfo/reader.py", line 50, in read_for
    raise InvalidTimezone(timezone)
pendulum.tz.zoneinfo.exceptions.InvalidTimezone: Invalid timezone "UTC+0"
```

Libfaketime is a faster alternative to freezegun (it use a C shared librare as a proxy on system calls)
However during it mocking itialization it change the `TZ` env var to `UTC+0` (not always though can be also `UTC-3`, `UTC+11` etc. but format stays the same):
https://github.com/simon-weber/python-libfaketime/blob/a974c9f098bf50ed34c19ff413d6dc08d8fdda00/libfaketime/__init__.py#L146

**Comment by sdispater** [comment]
Is `UTC+0` a valid timezone though? I don't think it is since it does not appear in the IANA database.

`GMT+0` and `GMT-0` are valid and `UTC-3` should be replaced by `Etc/GMT-3` (see https://github.com/sdispater/pytzdata/tree/master/pytzdata/zoneinfo/Etc)

**Comment by touilleMan** [comment]
Thanks for the answer, so I've opened an issue in python-libfaketime (https://github.com/simon-weber/python-libfaketime/issues/46)

**Comment by sdispater** [comment]
Also, just for information, you can use `with pendulum.test()` to mock the "now" datetime (see https://pendulum.eustace.io/docs/#testing)

**Comment by touilleMan** [comment]
@sdispater hoooo I didn't realized this feature was present, pendulum is really an awesome tool :smile: :tada:
