### ISSUE TITLE
IsADirectoryError while getting local timezone

### ISSUE THREAD

**Issue by aczapszys** [sdispater/pendulum#256]
Maybe related to https://github.com/sdispater/pendulum/commit/6ee68b9fdfb1bfd25db6c946d110cc4578a86958

I'm seeing an error with this test.py:
```
import pendulum
pendulum.now()
```
```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    pendulum.now()
  File "/mnt/iscsi/10_web_cem_dev/work/axc/cem-one-times/env/lib64/python3.6/site-packages/pendulum/__init__.py", line 207, in now
    dt = _datetime.datetime.now(local_timezone())
  File "/mnt/iscsi/10_web_cem_dev/work/axc/cem-one-times/env/lib64/python3.6/site-packages/pendulum/tz/__init__.py", line 59, in local_timezone
    return get_local_timezone()
  File "/mnt/iscsi/10_web_cem_dev/work/axc/cem-one-times/env/lib64/python3.6/site-packages/pendulum/tz/local_timezone.py", line 31, in get_local_timezone
    tz = _get_system_timezone()
  File "/mnt/iscsi/10_web_cem_dev/work/axc/cem-one-times/env/lib64/python3.6/site-packages/pendulum/tz/local_timezone.py", line 59, in _get_system_timezone
    return _get_unix_timezone()
  File "/mnt/iscsi/10_web_cem_dev/work/axc/cem-one-times/env/lib64/python3.6/site-packages/pendulum/tz/local_timezone.py", line 210, in _get_unix_timezone
    return Timezone('/'.join(tzpath))
  File "/mnt/iscsi/10_web_cem_dev/work/axc/cem-one-times/env/lib64/python3.6/site-packages/pendulum/tz/timezone.py", line 30, in __init__
    tz = read(name, extend=extended)
  File "/mnt/iscsi/10_web_cem_dev/work/axc/cem-one-times/env/lib64/python3.6/site-packages/pendulum/tz/zoneinfo/__init__.py", line 9, in read
    return Reader(extend=extend).read_for(name)
  File "/mnt/iscsi/10_web_cem_dev/work/axc/cem-one-times/env/lib64/python3.6/site-packages/pendulum/tz/zoneinfo/reader.py", line 52, in read_for
    return self.read(file_path)
  File "/mnt/iscsi/10_web_cem_dev/work/axc/cem-one-times/env/lib64/python3.6/site-packages/pendulum/tz/zoneinfo/reader.py", line 63, in read
    with open(file_path, 'rb') as fd:
IsADirectoryError: [Errno 21] Is a directory: '/mnt/iscsi/10_web_cem_dev/work/axc/cem-one-times/env/lib64/python3.6/site-packages/pytzdata/zoneinfo/Pacific'
```
This is the content of my `/etc/sysconfig/clock`:
```
ZONE="US/Pacific"
```

I think it should be trying to read `env/lib64/python3.6/site-packages/pytzdata/zoneinfo/US/Pacific`

**Comment by aczapszys** [comment]
I can confirm `test.py` works w/ pendulum 2.0.0

**Comment by leric** [comment]
I just got a similar error:  `IsADirectoryError: [Errno 21] Is a directory: '/etc/timezone'`
and found an empty directory at /etc/timezone/ which shouldn't be there, I deleted the directory to handle the error, but pendulum should be more careful with files.

**Comment by lsh-0** [comment]
The fix looks like it's here: https://github.com/sdispater/pytzdata/pull/11

But it's uncommitted.

Could it be committed please? alternately, could this ticket be re-opened?

**Comment by darkfeline** [comment]
I'm seeing this on pendulum-3.0.0 (as a dep for flexget).  Was the bug fixed or did this regress?

**Comment by aczapszys** [comment]
@darkfeline 
I think what you're seeing is an edge case that was not fixed.  You might want to open a new issue with you stack trace / description.

I presume that in your case, `/etc/localtime` is a symlink to something like `/usr/share/zoneinfo/US/Pacific`.
In that case, `_get_unix_timezone` calls `Timezone("Pacific")` to see if it's valid.
https://github.com/sdispater/pendulum/blob/3.0.0/src/pendulum/tz/local_timezone.py#L232

However, down in Python's `zoneinfo.load_tzdata`, it does not protect against its resource maybe being a directory (https://github.com/python/tzdata/tree/master/src/tzdata/zoneinfo/Pacific).  It throws an `IsADirectoryError` where it should have thrown a `ZoneInfoNotFoundError`.
https://github.com/python/cpython/blame/main/Lib/zoneinfo/_common.py#L13

Ideally, this fix would go in `zoneinfo`.  But in the mean time, you could add `IsADirectoryError` to  `_get_unix_timezone`'s `contextlib.suppress` call.
