### ISSUE TITLE
from_format() cannot parse YYYY-MM-DD[T]HH:mm:ssZ

### ISSUE THREAD

**Issue by nackjicholson** [sdispater/pendulum#266]
Install info:

```
[1] nackjicholson@Williams-MacBook-Pro-2152> poetry show pendulum                                                                                                                                                                                              ~/repos/intake
name        : pendulum                  
version     : 2.0.3                     
description : Python datetimes made easy

dependencies
 - python-dateutil >=2.6,<3.0
 - pytzdata >=2018.3
```

I used the same format string `YYYY-MM-DD[T]HH:mm:ssZ` to both format and parse the same datetime and it works for formatting but not for parsing. That was very unexpected.

```python
Python 3.6.5 (default, Apr 25 2018, 14:23:58) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pendulum
>>> dt = pendulum.datetime(2016, 2, 8, 14)
>>> dt_str = dt.format('YYYY-MM-DD[T]HH:mm:ssZ')
>>> dt_str
'2016-02-08T14:00:00+00:00'
>>> # COOL
... 
>>> same_dt = pendulum.from_format(dt_str, 'YYYY-MM-DD[T]HH:mm:ssZ')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nackjicholson/Library/Caches/pypoetry/virtualenvs/intake-py3.6/lib/python3.6/site-packages/pendulum/__init__.py", line 247, in from_format
    parts = _formatter.parse(string, fmt, now(), locale=locale)
  File "/Users/nackjicholson/Library/Caches/pypoetry/virtualenvs/intake-py3.6/lib/python3.6/site-packages/pendulum/formatting/formatter.py", line 405, in parse
    raise ValueError('String does not match format {}'.format(fmt))
ValueError: String does not match format YYYY-MM-DD[T]HH:mm:ssZ
>>> 
>>> # WHAT?!?!?
... 
>>> # But this works:
... 
>>> pendulum.parse(dt_str)
DateTime(2016, 2, 8, 14, 0, 0, tzinfo=Timezone('+00:00'))
>>> 
```

**Comment by nackjicholson** [comment]
I took a brief look at the _TOKENS and _FORMAT_RE in formatter.py
There is some tricky replacement stuff going on, and I'm not sure I understand enough to fix it.

**Comment by nackjicholson** [comment]
Thanks Sebastien! ☕️
