### ISSUE TITLE
from_format('12/2/2015 12:00:00 AM EST', 'M/D/YYYY h:mm:ss A zz')

### ISSUE THREAD

**Issue by nackjicholson** [sdispater/pendulum#279]
```
>>> pendulum.from_format('12/2/2015 12:00:00 AM EST', 'M/D/YYYY h:mm:ss A zz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nackjicholson/Library/Caches/pypoetry/virtualenvs/source-data-service-py3.6/lib/python3.6/site-packages/pendulum/__init__.py", line 256, in from_format
    parts = _formatter.parse(string, fmt, now(), locale=locale)
  File "/Users/nackjicholson/Library/Caches/pypoetry/virtualenvs/source-data-service-py3.6/lib/python3.6/site-packages/pendulum/formatting/formatter.py", line 400, in parse
    lambda m: self._replace_tokens(m.group(0), locale), escaped_fmt
  File "/Users/nackjicholson/Library/Caches/pypoetry/virtualenvs/source-data-service-py3.6/lib/python3.6/site-packages/pendulum/formatting/formatter.py", line 400, in <lambda>
    lambda m: self._replace_tokens(m.group(0), locale), escaped_fmt
  File "/Users/nackjicholson/Library/Caches/pypoetry/virtualenvs/source-data-service-py3.6/lib/python3.6/site-packages/pendulum/formatting/formatter.py", line 651, in _replace_tokens
    raise ValueError("Unsupported token: {}".format(token))
ValueError: Unsupported token: zz
```

This is from the master branch.

**Comment by nackjicholson** [comment]
```
nackjicholson@Williams-MacBook-Pro-299> poetry show pendulum                                                                                           ~/repos/source-data-service
name        : pendulum                  
version     : 2.0.4                     
description : Python datetimes made easy

dependencies
 - python-dateutil >=2.6,<3.0
 - pytzdata >=2018.3
```

```python
Python 3.6.6 (default, Oct  1 2018, 22:50:49) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pendulum
>>> dt = pendulum.from_format("12/12/18 2:50:00 PM PST", "M/D/YY h:mm:ss A zz")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nackjicholson/Library/Caches/pypoetry/virtualenvs/source-data-service-py3.6/lib/python3.6/site-packages/pendulum/__init__.py", line 256, in from_format
    parts = _formatter.parse(string, fmt, now(), locale=locale)
  File "/Users/nackjicholson/Library/Caches/pypoetry/virtualenvs/source-data-service-py3.6/lib/python3.6/site-packages/pendulum/formatting/formatter.py", line 403, in parse
    lambda m: self._replace_tokens(m.group(0), locale), escaped_fmt
  File "/Users/nackjicholson/Library/Caches/pypoetry/virtualenvs/source-data-service-py3.6/lib/python3.6/site-packages/pendulum/formatting/formatter.py", line 403, in <lambda>
    lambda m: self._replace_tokens(m.group(0), locale), escaped_fmt
  File "/Users/nackjicholson/Library/Caches/pypoetry/virtualenvs/source-data-service-py3.6/lib/python3.6/site-packages/pendulum/formatting/formatter.py", line 654, in _replace_tokens
    raise ValueError("Unsupported token: {}".format(token))
ValueError: Unsupported token: zz
>>> 
```

Working around all of this via some crazy specific and fragile date hacking code.

*datehacks.py*

```python
from dateutil.parser import parse

from .utc_offsets import UTC_OFFSETS


def parse_explicit_mdy(dt_str):
    return parse(dt_str, tzinfos=UTC_OFFSETS, dayfirst=False, yearfirst=False)


def parse_explicit_dmy(dt_str):
    return parse(dt_str, tzinfos=UTC_OFFSETS, dayfirst=True, yearfirst=False)
```

```python
    # FIXME pendulum bugs, can't format or parse contrary to documentation.
    # See: https://github.com/sdispater/pendulum/issues/279
    if fmt == "M/D/YYYY h:mm:ss A zz":
        return instance(datehacks.parse_explicit_mdy(dt_str))
    if fmt == "M/D/YYYY hh:mm:ss A zz":
        return instance(datehacks.parse_explicit_mdy(dt_str))
    if fmt == "M/D/YY h:mm:ss A zz":
        return instance(datehacks.parse_explicit_mdy(dt_str))
    if fmt == "DD-MMM-YY h:mm:ss A zz":
        return instance(datehacks.parse_explicit_dmy(dt_str))

    try:
        return from_format(dt_str, fmt, tz=tz_name)
    except ValueError:
        # If the above fails, sometimes this works
        # Pendulum bug: https://github.com/sdispater/pendulum/issues/266
        return parse(dt_str, tz=tz_name)

```

**Comment by altendky** [comment]
Some abbreviations are present in the regular `pendulum.timezones` list (in other words, `z`).
```
>>> tuple(tz for tz in pendulum.timezones if '/' not in tz and tz[:2].isupper())
('CET', 'CST6CDT', 'EET', 'EST', 'EST5EDT', 'GB', 'GB-Eire', 'GMT', 'GMT+0', 'GMT-0', 'GMT0', 'HST', 'MET', 'MST', 'MST7MDT', 'NZ', 'NZ-CHAT', 'PRC', 'PST8PDT', 'ROC', 'ROK', 'UCT', 'UTC', 'W-SU', 'WET')
```
But that list seems lacking enough for the US, let alone with a less US-centric view, to be not particularly useful.

I'm not sure there's a general solution to this as I don't believe the abbreviations are well defined enough to be unique.  Still, they certainly are used and the ambiguity could be overcome by allowing the caller to pass a mapping of unique abbreviations to unique names.  `{'CDT': 'America/Chicago'}` (hopefully that's a good example but...)  Optionally, regional default lists could be provided for easy use.

**Comment by altendky** [comment]
@setiat, I think my comment was that conceptually these time zones aren't really sensible.  They are not unique.

**Comment by setiat** [comment]
@altendky 
Yup, I agree
To resolve ambiguity, Is there any way in pendulum where I can pass tzonfo dict like its done in dateutil.parser.parse?

Also its been more that 2 years since this issue was opened...shouldn't pendulum remove "zz" from its list of accepted token..it is kind of misleading.

**Comment by yebei199** [comment]
> I agree that it is accurate for this issue to be in the open state. I don't have authority to make the fix happen and I have lots of other open source work I am more responsible for that needs my time. Sorry. `:[`我同意将此问题置于“未解决”状态是正确的。我没有权限修复此问题，而且我还有很多其他开源工作需要我投入时间。抱歉。 `:[`
> 
> (nitpick, this issue is three years old, not two)（挑剔一下，这个问题已经有三年了，而不是两年了）

This issue is seven years old, not three
