### ISSUE TITLE
from_format string does not match

### ISSUE THREAD

**Issue by Bobspadger** [sdispater/pendulum#283]
Version: 2.0.3

Reproduce:

```python
import pendulum
pendulum.from_format('2018-09-27T15:05:37.000Z', 'YYYY-MM-DD[T]HH:mm:ss.SSS[Z]')

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/alexhellier/GIT/ebaypaypal/venv/ebaypaypal343/lib/python3.4/site-packages/pendulum/__init__.py", line 247, in from_format
    parts = _formatter.parse(string, fmt, now(), locale=locale)
  File "/Users/alexhellier/GIT/ebaypaypal/venv/ebaypaypal343/lib/python3.4/site-packages/pendulum/formatting/formatter.py", line 405, in parse
    raise ValueError('String does not match format {}'.format(fmt))
ValueError: String does not match format YYYY-MM-DD[T]HH:mm:ss.SSS[Z]

```

Trying without the [] round the T and Z

```python
pendulum.from_format('2018-09-27T15:05:37.000Z', 'YYYY-MM-DDTHH:mm:ss.SSSZ')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/alexhellier/GIT/ebaypaypal/venv/ebaypaypal343/lib/python3.4/site-packages/pendulum/__init__.py", line 247, in from_format
    parts = _formatter.parse(string, fmt, now(), locale=locale)
  File "/Users/alexhellier/GIT/ebaypaypal/venv/ebaypaypal343/lib/python3.4/site-packages/pendulum/formatting/formatter.py", line 407, in parse
    re.sub(pattern, lambda m: self._get_parsed_values(m, parsed, locale, now), time)
  File "/Users/alexhellier/GIT/ebaypaypal/venv/ebaypaypal343/lib/python3.4/re.py", line 179, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/Users/alexhellier/GIT/ebaypaypal/venv/ebaypaypal343/lib/python3.4/site-packages/pendulum/formatting/formatter.py", line 407, in <lambda>
    re.sub(pattern, lambda m: self._get_parsed_values(m, parsed, locale, now), time)
  File "/Users/alexhellier/GIT/ebaypaypal/venv/ebaypaypal343/lib/python3.4/site-packages/pendulum/formatting/formatter.py", line 542, in _get_parsed_values
    self._get_parsed_value(token, m.group(index), parsed, now)
  File "/Users/alexhellier/GIT/ebaypaypal/venv/ebaypaypal343/lib/python3.4/site-packages/pendulum/formatting/formatter.py", line 590, in _get_parsed_value
    offset = ((int(off_hour) * 60) + int(off_minute)) * 60
ValueError: invalid literal for int() with base 10: ''

```

I feel like one of these should be working, but its not.

Top work by the way :)

**Comment by sdispater** [comment]
It should be fixed now
