### ISSUE TITLE
InvalidZoneinfoFile: Expected 0 bytes reading /.../pytzdata/zoneinfo/UTC, but got 0

### ISSUE THREAD

**Issue by lithammer** [sdispater/pendulum#300]
Versions:

- Python 2.7.5
- python-dateutil 2.7.5
- pytzdata 2018.7
- pendulum 2.0.3

OS: CentOS Linux release 7.5.1804 (Core)

```python
>>> pendulum.from_format("2018-01-01", "YYYY-MM-DD")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "env/lib/python2.7/site-packages/pendulum/__init__.py", line 247, in from_format
    parts = _formatter.parse(string, fmt, now(), locale=locale)
  File "env/lib/python2.7/site-packages/pendulum/__init__.py", line 207, in now
    dt = _datetime.datetime.now(local_timezone())
  File "env/lib/python2.7/site-packages/pendulum/tz/__init__.py", line 59, in local_timezone
    return get_local_timezone()
  File "env/lib/python2.7/site-packages/pendulum/tz/local_timezone.py", line 31, in get_local_timezone
    tz = _get_system_timezone()
  File "env/lib/python2.7/site-packages/pendulum/tz/local_timezone.py", line 59, in _get_system_timezone
    return _get_unix_timezone()
  File "env/lib/python2.7/site-packages/pendulum/tz/local_timezone.py", line 223, in _get_unix_timezone
    return Timezone(os.path.join(*tzpath))
  File "env/lib/python2.7/site-packages/pendulum/tz/timezone.py", line 30, in __init__
    tz = read(name, extend=extended)
  File "env/lib/python2.7/site-packages/pendulum/tz/zoneinfo/__init__.py", line 9, in read
    return Reader(extend=extend).read_for(name)
  File "env/lib/python2.7/site-packages/pendulum/tz/zoneinfo/reader.py", line 52, in read_for
    return self.read(file_path)
  File "env/lib/python2.7/site-packages/pendulum/tz/zoneinfo/reader.py", line 64, in read
    return self._parse(fd)
  File "env/lib/python2.7/site-packages/pendulum/tz/zoneinfo/reader.py", line 115, in _parse
    type_idx = self._parse_type_idx(fd, hdr.transitions)
  File "env/lib/python2.7/site-packages/pendulum/tz/zoneinfo/reader.py", line 198, in _parse_type_idx
    buff = self._check_read(fd, n)
  File "env/lib/python2.7/site-packages/pendulum/tz/zoneinfo/reader.py", line 77, in _check_read
    nbytes, fd.name, len(result) if result else 0
pendulum.tz.zoneinfo.exceptions.InvalidZoneinfoFile: Expected 0 bytes reading env/lib/python2.7/site-packages/pytzdata/zoneinfo/UTC, but got 0
>>> with open('env/lib/python2.7/site-packages/pytzdata/zoneinfo/UTC') as f:
...     f.read()
...
'TZif2\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00UTC\x00\x00\x00TZif2\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00UTC\x00\x00\x00\nUTC0\n'
```

**Comment by lithammer** [comment]
It works if I downgrade pytzdata to 2018.5.

**Comment by rmmcnulty9** [comment]
Is this going to be patched? It looks like your poetry file needs to be locked at the working version of `pytxdata`: https://github.com/sdispater/pendulum/blob/2.0.3/pyproject.toml

**Comment by rmmcnulty9** [comment]
Great, thanks for the fast turn around! It might still be a good idea to lock dependency versions to avoid upstream breaking changes. Then you can upgrade dependencies at your own pace rather than frantically addressing changes :smile:
