### ISSUE TITLE
String parse BUG!

### ISSUE THREAD

**Issue by dongli** [sdispater/pendulum#328]
Try the following tests which works in 1.x, but breaks in 2.x.

Works:
1.x:
```
In [6]: pendulum.from_format('190022215', '%y%j%H%M')
/usr/local/bin/ipython:1: DeprecationWarning: Using the classic formatter in from_format() is deprecated and will no longer be possible in version 2.0. Use the alternative formatter instead.
  #!/usr/bin/python36
Out[6]: <Pendulum [2019-01-02T22:15:00+00:00]>
```
2.x:
```
>>> pendulum.from_format('191222215', 'YYDDDDHHmm')
DateTime(2019, 5, 2, 22, 15, 0, tzinfo=Timezone('UTC'))
```

Do not works:
2.x:
```
>>> pendulum.from_format('190022215', 'YYDDDDHHmm')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/pendulum/__init__.py", line 256, in from_format
    parts = _formatter.parse(string, fmt, now(), locale=locale)
  File "/usr/local/lib64/python3.6/site-packages/pendulum/formatting/formatter.py", line 411, in parse
    return self._check_parsed(parsed, now)
  File "/usr/local/lib64/python3.6/site-packages/pendulum/formatting/formatter.py", line 472, in _check_parsed
    "{}-{}".format(validated["year"], parsed["day_of_year"])
  File "/usr/local/lib64/python3.6/site-packages/pendulum/parser.py", line 20, in parse
    return _parse(text, **options)
  File "/usr/local/lib64/python3.6/site-packages/pendulum/parser.py", line 36, in _parse
    parsed = base_parse(text, **options)
  File "/usr/local/lib64/python3.6/site-packages/pendulum/parsing/__init__.py", line 70, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/usr/local/lib64/python3.6/site-packages/pendulum/parsing/__init__.py", line 124, in _parse
    raise ParserError("Unable to parse string [{}]".format(text))
pendulum.parsing.exceptions.ParserError: Unable to parse string [2019-2]
```
What could I do when my production system meets this bug at the beginning of the year : (

**Comment by neurotik1** [comment]
I just ran into this issue as well, but it looks like a recent commit (https://github.com/sdispater/pendulum/commit/23f290f8063a52c77a2ae7de7a790f91a84dc817) has fixed the problem. You could either use the master branch or implement the fix on your local copy in order to get it working until the next release.

**Comment by dongli** [comment]
@neurotik1 Thanks for your information! I have fixed this bug by a nasty way in my production system, so waiting for the new version~

**Comment by homeworkprod** [comment]
v2.0.5 has been released with this fix, so I think this issue can be closed.
