### ISSUE TITLE
Installing pendulum==1.4.4 fails on Python 2.7 OSX 10.13.6 pip 19.0.1

### ISSUE THREAD

**Issue by bilow-factual** [sdispater/pendulum#335]
I'm trying to set up a local environment for airflow using the following command: 

```
source deactivate
conda env remove -n airflow_env -y
conda create -n airflow_env -y python=2.7

source activate airflow_env
conda install pip -f

export AIRFLOW_DEPS="crypto,postgres,hive,jdbc,mysql,ssh,devel_hadoop,hdfs,kerberos,ldap,s3,slack,password"
export AIRFLOW_VERSION="1.10.2"
export AIRFLOW_GPL_UNIDECODE=yes

pip install -U pip setuptools wheel requests \
    && pip install pytz \
    && pip install pyOpenSSL \
    && pip install ndg-httpsclient \
    && pip install pyasn1 \
    && pip install pandas \
    && pip install apache-airflow[${AIRFLOW_DEPS}]==${AIRFLOW_VERSION} \
    && pip install 'redis>=2.10.5,<3' \
    && pip install awscli --upgrade
```

This is dying with:

```
Collecting pendulum==1.4.4 (from apache-airflow[crypto,devel_hadoop,hdfs,hive,jdbc,kerberos,ldap,mysql,password,postgres,s3,slack,ssh]==1.10.2)
  Using cached https://files.pythonhosted.org/packages/85/a5/9fc15751f9725923b170ad37d6c61031fc9e941bafd5288ca6ee51233284/pendulum-1.4.4.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /Users/bilow/anaconda3/envs/airflow_env/bin/python /Users/bilow/anaconda3/envs/airflow_env/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/gz/hjzlbwrn0kx12wtmwhk0mkdw0000gr/T/tmp5A6aAT:
  Traceback (most recent call last):
    File "/Users/bilow/anaconda3/envs/airflow_env/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/Users/bilow/anaconda3/envs/airflow_env/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/bilow/anaconda3/envs/airflow_env/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/gz/hjzlbwrn0kx12wtmwhk0mkdw0000gr/T/pip-build-env-qMF_oz/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 115, in get_requires_for_build_wheel
      return _get_build_requires(config_settings, requirements=['wheel'])
    File "/private/var/folders/gz/hjzlbwrn0kx12wtmwhk0mkdw0000gr/T/pip-build-env-qMF_oz/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 101, in _get_build_requires
      _run_setup()
    File "/private/var/folders/gz/hjzlbwrn0kx12wtmwhk0mkdw0000gr/T/pip-build-env-qMF_oz/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 85, in _run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 47, in <module>
      from build import *
    File "/Users/bilow/anaconda3/envs/airflow_env/lib/python2.7/site-packages/pip/_vendor/pep517/build.py", line 7, in <module>
      from pip._vendor import pytoml
  ImportError: No module named pip._vendor
```

```
$ pip --version
pip 19.0.1 from /Users/bilow/anaconda3/envs/airflow_env/lib/python2.7/site-packages/pip (python 2.7)
$ python --version
Python 2.7.15 :: Anaconda, Inc.
```

I'm on OSX 10.13.6; for the record, this works fine running inside a stripped down docker container.

Thanks!

**Comment by SBlangkon** [comment]
Try to run as administrator in command prompt
