### ISSUE TITLE
error installing pendulum: jsonschema has no 'Draft7Validator'

### ISSUE THREAD

**Issue by radix** [sdispater/pendulum#337]
I'm not really sure which package's problem this is, but the build error is happening while installing pendulum in my CI environment.

The `pip` version in my CI environment is `9.0.1`. (**EDIT**: the same behavior occurs on 19.0.1, **EDIT AGAIN**: turns out my CI auto-upgrades pip, so this might be introduced by a newer pip version).

My project doesn't depend directly on `pendulum`, but rather on `maya==0.3.3`. I haven't changed any of my dependencies in a while, but something must have changed somewhere else (I only pin my direct dependencies, not my entire dependency tree).

Here is the relevant snippet from `pip install`:

```
Collecting pendulum (from maya==0.3.3->-r jbcli/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/5b/57/71fc910edcd937b72aa0ef51c8f5734fbd8c011fa1480fce881433847ec8/pendulum-2.0.4.tar.gz (75kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  Complete output from command /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp2gXYyc:
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-WgkDnN/overlay/lib/python2.7/site-packages/poetry/masonry/api.py", line 23, in get_requires_for_build_wheel
      poetry = Poetry.create(".")
    File "/tmp/pip-build-env-WgkDnN/overlay/lib/python2.7/site-packages/poetry/poetry.py", line 106, in create
      cls.check(local_config)
    File "/tmp/pip-build-env-WgkDnN/overlay/lib/python2.7/site-packages/poetry/poetry.py", line 226, in check
      validation_errors = validate_object(config, "poetry-schema")
    File "/tmp/pip-build-env-WgkDnN/overlay/lib/python2.7/site-packages/poetry/json/__init__.py", line 25, in validate_object
      validator = jsonschema.Draft7Validator(schema)
  AttributeError: 'module' object has no attribute 'Draft7Validator'
```

**Comment by radix** [comment]
This seems related to https://github.com/sdispater/poetry/issues/532, but I'm confused because nothing in my project or CI explicitly uses poetry.

**Comment by peter-slovak** [comment]
In my case, the problem was an old system-global version of `jsonschema` - `pip` in any virtualenv used it because no local version was available.
Running `pip install -u jsonschema` on system-wide level (no virtualenv) fixed the problem.

**Comment by Secrus** [comment]
Should be fine in current versions.
