### ISSUE TITLE
Error installing on ubuntu 16.04  "ValueError: Attempted relative import in non-package"

### ISSUE THREAD

**Issue by skinney6** [sdispater/pendulum#338]
Below 1.4.3 or above 2.* pip installs fine but 1.4.3 to 1.5.1 I get this `ValueError: Attempted relative import in non-package`. 
This us on ubuntu 16.02
python 2.7
```
$ pip install pendulum==1.4.3
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pendulum==1.4.3
  Downloading https://files.pythonhosted.org/packages/b8/40/828bf56af477fb85618126ad8162b7cf5bed84c28a94bfa42f72ad42010c/pendulum-1.4.3.tar.gz (74kB)
    100% |████████████████████████████████| 81kB 4.8MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /home/ubuntu/test/bin/python2 /home/ubuntu/test/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsIXmEW:
  Traceback (most recent call last):
    File "/home/ubuntu/test/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/ubuntu/test/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/ubuntu/test/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/home/ubuntu/test/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 115, in get_requires_for_build_wheel
      return _get_build_requires(config_settings, requirements=['wheel'])
    File "/home/ubuntu/test/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 101, in _get_build_requires
      _run_setup()
    File "/home/ubuntu/test/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 85, in _run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 47, in <module>
      from build import *
    File "/home/ubuntu/test/lib/python2.7/site-packages/pip/_vendor/pep517/build.py", line 12, in <module>
      from .envbuild import BuildEnvironment
  ValueError: Attempted relative import in non-package
```

**Comment by gingerjoos** [comment]
This seems to be an incompatibility with pip 19, pip 18 works fine. Downgrading to `pip==18.1` works.

**Comment by gingerjoos** [comment]
See https://github.com/sdispater/pendulum/issues/335 . By the way, this happens on Ubuntu 18.04 as well
