### ISSUE TITLE
ParserError: Unable to parse string [2016-1-17]

### ISSUE THREAD

**Issue by elidchan** [sdispater/pendulum#349]
`pendulum.parse('2016-1-17')` is the first example under [Why not Arrow?](https://github.com/sdispater/pendulum#why-not-arrow)

This works in Python 3.7, but fails in Python 2.7.15:
```
pendulum.parse('2016-1-17')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/elichan/code/iz2/.virtualenv/lib/python2.7/site-packages/pendulum/parser.py", line 20, in parse
    return _parse(text, **options)
  File "/Users/elichan/code/iz2/.virtualenv/lib/python2.7/site-packages/pendulum/parser.py", line 36, in _parse
    parsed = base_parse(text, **options)
  File "/Users/elichan/code/iz2/.virtualenv/lib/python2.7/site-packages/pendulum/parsing/__init__.py", line 70, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/Users/elichan/code/iz2/.virtualenv/lib/python2.7/site-packages/pendulum/parsing/__init__.py", line 124, in _parse
    raise ParserError("Unable to parse string [{}]".format(text))
ParserError: Unable to parse string [2016-1-17]
```

**Comment by apnewberry** [comment]
You can use `strict=False`.

```
>>> pendulum.parse('2016-1-17', strict=False)
DateTime(2016, 1, 17, 0, 0, 0, tzinfo=Timezone('UTC'))
```

**Comment by elidchan** [comment]
Good to know! The README is out of date in this case. But I still think this is awkward as none of the other examples require this flag. It weakens the usability argument in my opinion.

Normally, I'd be in favor of greater strictness as the default. However, it doesn't make sense that fixed-width should be considered more strict than variable width. They're simply two different formats.

Since '2016-1-17' is unambiguously the same as `2016-01-17`, pendulum should just do the right thing without requiring special configuration.
