### ISSUE TITLE
Trouble installing on Mac python 2.7.10

### ISSUE THREAD

**Issue by dveight** [sdispater/pendulum#369]
Hello, 
I am trying to install apache-airflow but when it gets to installing pendulum it errors out giving me this traceback.

The command I ran was:

```
sudo -H pip install apache-airflow
```

```
Collecting pendulum==1.4.4 (from apache-airflow)
  Using cached https://files.pythonhosted.org/packages/85/a5/9fc15751f9725923b170ad37d6c61031fc9e941bafd5288ca6ee51233284/pendulum-1.4.4.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Complete output from command /usr/bin/python /Library/Python/2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmprHj_dK:
  ERROR: Traceback (most recent call last):
    File "/Library/Python/2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 18, in <module>
      import shutil
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 12, in <module>
      import collections
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 8, in <module>
      from _collections import deque, defaultdict
  ImportError: No module named _collections
  ----------------------------------------
ERROR: Command "/usr/bin/python /Library/Python/2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmprHj_dK" failed with error code 1 in /private/tmp/pip-install-jYzkf1/pendulum
```

Pip is version 19.1 from /Library/Python/2.7/site-packages/pip (python 2.7)
My Mac OS X is 10.14 (Mojave)

I've tried to extend my pythonpath to look at:
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload

 as per another question similar to this. But still no dice.

If I try to install only pendulum I get the same error.

Any help would be greatly appreciated. 

Thank you!

**Comment by Sakibs** [comment]
Were you able to figure this out? I'm getting the same issue as well.

Whats weird is when I start python commandline interpreter and import _collections I see it

```
$ python
Python 2.7.10 (default, Feb 22 2019, 21:55:15) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import _collections
>>> from _collections import deque, defaultdict
>>> 
```

**Comment by Secrus** [comment]
Seems like a broken Python installation. Also, Python 2.7 won't be supported in the upcoming release.
