### ISSUE TITLE
pendulum.now invalid argument "unix_time"

### ISSUE THREAD

**Issue by scktt** [sdispater/pendulum#53]
pendulum unable to create any date time instances due to unix_time not being loaded correctly on windows, seems okay under unix.

**Win7 x64 Ent**

```
(.env) C:\projects\scripts\python\timescamp (develop)
λ pip freeze
pendulum==0.6.1
python-dateutil==2.5.3
pytz==2016.6.1
requests==2.11.1
six==1.10.0
tzlocal==1.2.2
```

```
(.env) C:\projects\scripts\python\timescamp (develop)
λ python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pendulum
>>> pendulum.now()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\projects\scripts\python\timescamp\.env\lib\site-packages\pendulum\pendulum.py", line 287, in now
    return cls.instance(dt, tz)
  File "C:\projects\scripts\python\timescamp\.env\lib\site-packages\pendulum\pendulum.py", line 223, in instance
    tzinfo=tz
  File "C:\projects\scripts\python\timescamp\.env\lib\site-packages\pendulum\pendulum.py", line 173, in __init__
    self._tz = self._safe_create_datetime_zone(tzinfo)
  File "C:\projects\scripts\python\timescamp\.env\lib\site-packages\pendulum\pendulum.py", line 100, in _safe_create_datetime_zone
    return cls._local_timezone()
  File "C:\projects\scripts\python\timescamp\.env\lib\site-packages\pendulum\pendulum.py", line 119, in _local_timezone
    return local_timezone()
  File "C:\projects\scripts\python\timescamp\.env\lib\site-packages\pendulum\tz\__init__.py", line 25, in local_timezone
    return LocalTimezone.get()
  File "C:\projects\scripts\python\timescamp\.env\lib\site-packages\pendulum\tz\local_timezone.py", line 29, in get
    cls._cache = Timezone.load(cls.get_local_tz_name())
  File "C:\projects\scripts\python\timescamp\.env\lib\site-packages\pendulum\tz\timezone.py", line 67, in load
    utc_transition_times) = Loader.load(name)
  File "C:\projects\scripts\python\timescamp\.env\lib\site-packages\pendulum\tz\loader.py", line 37, in load
    return cls._load(f)
  File "C:\projects\scripts\python\timescamp\.env\lib\site-packages\pendulum\tz\loader.py", line 122, in _load
    pre_transition_type_index
  File "C:\projects\scripts\python\timescamp\.env\lib\site-packages\pendulum\tz\transition.py", line 44, in __init__
    self._utc_time = datetime.utcfromtimestamp(unix_time)
OSError: [Errno 22] Invalid argument
```

**Synology x86_64 (unix)**
```
(test) scott@pandora:~/scripts/python/pendulum$ pip freeze
pendulum==0.6.1
python-dateutil==2.5.3
pytz==2016.6.1
six==1.10.0
tzlocal==1.2.2
```

```
(test) scott@pandora:~/scripts/python/pendulum$ python3
Python 3.5.1 (default, Feb 23 2016, 17:47:45)
[GCC 4.9.3 20150311 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pendulum
>>> pendulum.now()
<Pendulum [2016-09-21T09:33:08.239546+10:00]>
>>>
```

**Comment by sdispater** [comment]
Could you execute the following in both cases?

```python
>>> from pendulum.tz import LocalTimezone
>>> print(LocalTimezone.get_local_tz_name())
```

**Comment by scktt** [comment]
**Windows**
```
>>> from pendulum.tz import LocalTimezone
>>> print(LocalTimezone.get_local_tz_name())
Australia/Sydney
```

**Unix**
```
>>> from pendulum.tz import LocalTimezone
>>> print(LocalTimezone.get_local_tz_name())
<Timezone [Australia/Sydney]>
```

**Comment by sdispater** [comment]
OK. So it seems `datetime.utcfromtimestamp()` does not accept negative timestamps on Windows for some reason. It works fine on other systems.

I will try to make a workaround to fix this.

**Comment by sdispater** [comment]
I just pushed a fix on `master` that should fix the issue.

Can you test it and confirm?

**Comment by scktt** [comment]
thanks @sdispater, that looks to have fixed the issue.

```python
(.env) C:\projects\timetracking\primetime\pendulum (master)
λ git log -1
commit 5b90e397e440c27673b2dd4332745dd5f70c95a1
Author: Sébastien Eustace <sebastien@eustace.io>
Date:   Tue Sep 20 23:56:49 2016 -0500

    Fixes Loader class on Windows.

(.env) C:\projects\timetracking\primetime\pendulum (master)
λ python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pendulum
>>> pendulum.now()
<Pendulum [2016-09-21T15:05:53.545422+10:00]>
>>>
```

**Comment by sdispater** [comment]
Version `0.6.2` is out with the fix included.
