### ISSUE TITLE
Exception when local time set to "Etc/UTC"

### ISSUE THREAD

**Issue by brunns** [sdispater/pendulum#62]
OS X 10.11.6, Python 3.5.1, Pendulum 0.6.4

```
sudo ln -sf /usr/share/zoneinfo/Etc/UTC /etc/localtime
python -c 'import pendulum; pendulum.now().add(seconds=3)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gavin/Development/MarksAndSpencer/cfto-browse/venv/lib/python3.5/site-packages/pendulum/pendulum.py", line 1446, in add
    dt = self._tz.convert(dt)
  File "/Users/gavin/Development/MarksAndSpencer/cfto-browse/venv/lib/python3.5/site-packages/pendulum/tz/timezone.py", line 93, in convert
    converted = self._convert(dt)
  File "/Users/gavin/Development/MarksAndSpencer/cfto-browse/venv/lib/python3.5/site-packages/pendulum/tz/timezone.py", line 218, in _convert
    return dt.astimezone(self)
  File "/Users/gavin/Development/MarksAndSpencer/cfto-browse/venv/lib/python3.5/site-packages/pendulum/tz/timezone.py", line 301, in fromutc
    tr = self._transitions[idx]
IndexError: tuple index out of range
```

**Comment by sdispater** [comment]
That's strange. I will look into it and get back to you.

**Comment by sdispater** [comment]
It was a problem with some timezone files that do not specify transitions (only transition types).

I just pushed a fix on the `master` branch (042a96686df00e20aa6eecd7271be09586b01722). It will be included in the next bugfix release.

**Comment by brunns** [comment]
Excellent, thank you. I'll try it.

**Comment by brunns** [comment]
Works a treat. Thanks again.

**Comment by sdispater** [comment]
Version `0.6.5` released.
