### ISSUE TITLE
Failed to install pendulum in fips mode

### ISSUE THREAD

**Issue by zl2705** [sdispater/pendulum#642]
- [x ] I am on the [latest](https://github.com/sdispater/pendulum/releases/latest) Pendulum version.
- [x ] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**:  Red Hat Enterprise Linux release 8.4 
- **Pendulum version**: pendulum-2.1.2

## Issue
pip install pendulum
Collecting pendulum
  Using cached pendulum-2.1.2.tar.gz (81 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1

  [32 lines of output]
  Traceback (most recent call last):
    ......
    File "/tmp/pip-build-env-754w8v8e/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
      poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
    File "/tmp/pip-build-env-754w8v8e/overlay/lib/python3.10/site-packages/poetry/core/factory.py", line 62, in create_poetry
      package = self.configure_package(
    File "/tmp/pip-build-env-754w8v8e/overlay/lib/python3.10/site-packages/poetry/core/factory.py", line 156, in configure_package
      cls._add_package_group_dependencies(
    File "/tmp/pip-build-env-754w8v8e/overlay/lib/python3.10/site-packages/poetry/core/factory.py", line 98, in _add_package_group_dependencies
      package.python_versions = _constraint
    File "/tmp/pip-build-env-754w8v8e/overlay/lib/python3.10/site-packages/poetry/core/packages/project_package.py", line 62, in python_versions
      self._python_marker = parse_marker(
    File "/tmp/pip-build-env-754w8v8e/overlay/lib/python3.10/site-packages/poetry/core/version/markers.py", line 795, in parse_marker
      parsed = _parser.parse(marker)
    File "/tmp/pip-build-env-754w8v8e/overlay/lib/python3.10/site-packages/poetry/core/version/parser.py", line 27, in parse
      self._lark = Lark.open(
    File "/tmp/pip-build-env-754w8v8e/overlay/lib/python3.10/site-packages/poetry/core/_vendor/lark/lark.py", line 548, in open
      return cls(f, **options)
    File "/tmp/pip-build-env-754w8v8e/overlay/lib/python3.10/site-packages/poetry/core/_vendor/lark/lark.py", line 333, in __init__
      self.grammar, used_files = load_grammar(grammar, self.source_path, self.options.import_paths, self.options.keep_all_tokens)
    File "/tmp/pip-build-env-754w8v8e/overlay/lib/python3.10/site-packages/poetry/core/_vendor/lark/load_grammar.py", line 1408, in load_grammar
      builder.load_grammar(grammar, source)
    File "/tmp/pip-build-env-754w8v8e/overlay/lib/python3.10/site-packages/poetry/core/_vendor/lark/load_grammar.py", line 1248, in load_grammar
      self.do_import(dotted_path, base_path, aliases, mangle)
    File "/tmp/pip-build-env-754w8v8e/overlay/lib/python3.10/site-packages/poetry/core/_vendor/lark/load_grammar.py", line 1315, in do_import
      h = hashlib.md5(text.encode('utf8')).hexdigest()
  ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Secrus** [comment]
I am not sure what exactly FIPS mode is, but a quick look into it makes me think that this is not exactly a Pendulum problem, but rather Poetry or Lark.

**Comment by zl2705** [comment]
FIPS (Federal Information Processing Standard) 140-2 is the benchmark for validating the effectiveness of cryptographic hardware.
[root@localhost ~]# fipscheck
usage: fipscheck [-s <hmac-suffix>] <paths-to-files>
fips mode is on
[root@localhost ~]# fips-mode-setup --is-enabled
[root@localhost ~]# echo $?
0

This is an installation problem. 
I use a workaround method to install it now. First disable fips and install Pendulum, and then re-enable fips.

**Comment by Secrus** [comment]
Should work fine with FIPS now.
