### ISSUE TITLE
AttributeError when using utcoffset

### ISSUE THREAD

**Issue by regnarock** [sdispater/pendulum#65]
Sample code to reproduce error:

$> python
```
import pendulum
tz = pendulum.timezone('Europe/Paris')
tz.utcoffset(pendulum.utcnow())
```

Exception:
> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thomaswilgenbus/.pyenv/versions/tex-connector-acs/lib/python2.7/site-packages/pendulum/tz/timezone.py", line 283, in utcoffset
    return dt.adjusted_offset
AttributeError: 'Pendulum' object has no attribute 'adjusted_offset'

**Comment by regnarock** [comment]
Fixed in [PR 66](https://github.com/sdispater/pendulum/pull/66)
