### ISSUE TITLE
time-machine still in project dependencies?

### ISSUE THREAD

**Issue by philipbjorge** [sdispater/pendulum#782]
## Issue

We use the project `liccheck` to validate our dependency licenses.
With the upgrade to Pendulum 3.0, this is now failing.

## Repro
`liccheck -r requirements.txt`

```
pendulum==3.0.0 ; python_version >= "3.10" and python_version < "3.11"
```

```
❯ poetry run liccheck -r requirements.txt
gathering licenses...
Traceback (most recent call last):
  File "/workspaces/marketplace/.venv/bin/liccheck", line 8, in <module>
    sys.exit(main())
  File "/workspaces/marketplace/.venv/lib/python3.10/site-packages/liccheck/command_line.py", line 529, in main
    sys.exit(run(args))
  File "/workspaces/marketplace/.venv/lib/python3.10/site-packages/liccheck/command_line.py", line 509, in run
    return process(
  File "/workspaces/marketplace/.venv/lib/python3.10/site-packages/liccheck/command_line.py", line 317, in process
    pkg_info = get_packages_info(requirement_file, no_deps)
  File "/workspaces/marketplace/.venv/lib/python3.10/site-packages/liccheck/command_line.py", line 195, in get_packages_info
    packages = [transform(dist) for dist in resolve_func(requirements)]
  File "/workspaces/marketplace/.venv/lib/python3.10/site-packages/liccheck/command_line.py", line 195, in <listcomp>
    packages = [transform(dist) for dist in resolve_func(requirements)]
  File "/workspaces/marketplace/.venv/lib/python3.10/site-packages/liccheck/requirements.py", line 51, in resolve
    for dist in pkg_resources.working_set.resolve(requirements):
  File "/workspaces/marketplace/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
  File "/workspaces/marketplace/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 870, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'time-machine>=2.6.0; implementation_name != "pypy"' distribution was not found and is required by pendulum
```

https://github.com/dhatim/python-license-check/blob/master/liccheck/requirements.py#L51

## Notes

[I see that this PR made the testing helpers optional.](https://github.com/sdispater/pendulum/pull/778/files)

I'm wondering if the inclusion of `time-machine` in the project dependencies is the cause of the issue.

https://github.com/sdispater/pendulum/blob/3e3fec6a5b66759078c5ae39c736ca95b78adbef/pyproject.toml#L25

**Comment by rafrafek** [comment]
It breaks my CI/CD:

```
Collecting time-machine>=2.6.0 (from pendulum==3.0.0->-r requirements.txt (line 47))
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    time-machine>=2.6.0 from https://files.pythonhosted.org/packages/d1/5b/869fac3fe82c91cefb9e0319f63a8f8905e12b45467d4d3b42b060cfa4ce/time_machine-2.13.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from pendulum==3.0.0->-r requirements.txt (line 47))
```

**Comment by jall** [comment]
I have the same issue as @rafrafek 

In our case, Poetry installs are breaking because `--require-hashes` is being set by default (and is the behaviour we want for CI)

**Comment by ZeoX06** [comment]
Hi,
we have installation issues with Pendulum 3.0.0 because our installation is breaking as time-machine is upgraded to 2.15.0 today.

Force downgrade to time-machine==2.14.2 is working as expected.

**Comment by edgarrmondragon** [comment]
> Also in poetry.lock the version looks like it is fixed to 2.13 but this seems not the case:\nhttps://github.com/sdispater/pendulum/blob/3.0.0/poetry.lock#L1015-L1016

The `poetry.lock` file is not used when installing Pendulum from PyPI, and only the requirement in `pyproject.toml` is relevant.

**Comment by pm-incyan** [comment]
> we have installation issues with Pendulum 3.0.0 because our installation is breaking as time-machine is upgraded to 2.15.0 today

I've just found this thread because of the same issue. I've done a little further digging...

When pendulum is installed using poetry, all is well, and the `time-machine` dependency is not installed unless you ask for it.

However if you install pendulum using pip, the `time-machine` dependency is always installed, even though it's only used for testing.

Since `time-machine` is now part of the test dependencies (https://github.com/sdispater/pendulum/blob/3e3fec6a5b66759078c5ae39c736ca95b78adbef/pyproject.toml#L59) can we simply remove the main dependency at:

- https://github.com/sdispater/pendulum/blob/3e3fec6a5b66759078c5ae39c736ca95b78adbef/pyproject.toml#L52
- https://github.com/sdispater/pendulum/blob/3e3fec6a5b66759078c5ae39c736ca95b78adbef/pyproject.toml#L25

I note that the imports are already protected in testing modules and gracefully fall back when the optional dep is not installed:

- https://github.com/sdispater/pendulum/blob/master/src/pendulum/testing/traveller.py
- https://github.com/sdispater/pendulum/blob/master/tests/datetime/test_construct.py

**Comment by Secrus** [comment]
This is now fixed on the master branch and will be included in the next release.
