### ISSUE TITLE
Duration division, multiplication and mod broken for month lengths.

### ISSUE THREAD

**Issue by gazpachoking** [sdispater/pendulum#799]
- [x] I am on the [latest](https://github.com/sdispater/pendulum/releases/latest) Pendulum version.
- [x] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.

- **OS Version**: Windows 11
- **Pendulum version**: 3.0.0

## Issue
When doing math on `Duration` objects, months are ignored. This is because it uses the `_to_microseconds` method which ignores the `months` attribute.
https://github.com/sdispater/pendulum/blob/3e3fec6a5b66759078c5ae39c736ca95b78adbef/src/pendulum/duration.py#L356-L357
e.g. :
```python
>>> pendulum.Duration(years=1)/pendulum.Duration(months=1)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.2.2\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Users\chase\PycharmProjects\Flexget\py310\lib\site-packages\pendulum\duration.py", line 419, in __truediv__
    float, usec / other._to_microseconds()  # type: ignore[attr-defined]
ZeroDivisionError: division by zero

>>> pendulum.Duration(months=1)*3.0
Duration()
```

**Comment by ruaridhw** [comment]
It should be relatively straight forward to defer to `.total_seconds()` since this already makes use of the years and months attributes correctly. I do agree that the number of microseconds (or seconds) in a month or year is ambiguous however pendulum already hardcodes these to be month=30days, year=365days. So given that, it should be possible to divide months by months, for example.
